name: 'Snowflake'
description: 'Github Action to enforce Martin''s snowflake formatting rules'
author: 'Martin Algesten <martin@algesten.com>'
inputs:
  line_width_rules:
    description: 'Line width rules in format "*.ext:width;DEFAULT=width"'
    required: true
    default: 'CHANGELOG.md:80;*.md:110;*.rs:110;*.toml:110;DEFAULT=110'
  check_pr_only:
    description: 'If true, only checks files and lines changed in the PR'
    required: false
    default: 'true'
outputs:
  line_width_result:
    description: 'Result of line width check'
  rust_import_result:
    description: 'Result of Rust import style check'
runs:
  using: 'node20'
  main: 'index.js'
branding:
  icon: 'check-square'
  color: 'green'